// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/gateway_discovery.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistryHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryHeartbeatRequest) Reset() {
	*x = RegistryHeartbeatRequest{}
	mi := &file_proto_gateway_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryHeartbeatRequest) ProtoMessage() {}

func (x *RegistryHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*RegistryHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *RegistryHeartbeatRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *RegistryHeartbeatRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegistryHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryHeartbeatResponse) Reset() {
	*x = RegistryHeartbeatResponse{}
	mi := &file_proto_gateway_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryHeartbeatResponse) ProtoMessage() {}

func (x *RegistryHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*RegistryHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *RegistryHeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_proto_gateway_discovery_proto protoreflect.FileDescriptor

const file_proto_gateway_discovery_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/gateway_discovery.proto\x12\vgeostreamdb\"S\n" +
	"\x18RegistryHeartbeatRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"?\n" +
	"\x19RegistryHeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2h\n" +
	"\bRegistry\x12\\\n" +
	"\tHeartbeat\x12%.geostreamdb.RegistryHeartbeatRequest\x1a&.geostreamdb.RegistryHeartbeatResponse\"\x00B\x13Z\x11geostreamdb/protob\x06proto3"

var (
	file_proto_gateway_discovery_proto_rawDescOnce sync.Once
	file_proto_gateway_discovery_proto_rawDescData []byte
)

func file_proto_gateway_discovery_proto_rawDescGZIP() []byte {
	file_proto_gateway_discovery_proto_rawDescOnce.Do(func() {
		file_proto_gateway_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_discovery_proto_rawDesc), len(file_proto_gateway_discovery_proto_rawDesc)))
	})
	return file_proto_gateway_discovery_proto_rawDescData
}

var file_proto_gateway_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gateway_discovery_proto_goTypes = []any{
	(*RegistryHeartbeatRequest)(nil),  // 0: geostreamdb.RegistryHeartbeatRequest
	(*RegistryHeartbeatResponse)(nil), // 1: geostreamdb.RegistryHeartbeatResponse
}
var file_proto_gateway_discovery_proto_depIdxs = []int32{
	0, // 0: geostreamdb.Registry.Heartbeat:input_type -> geostreamdb.RegistryHeartbeatRequest
	1, // 1: geostreamdb.Registry.Heartbeat:output_type -> geostreamdb.RegistryHeartbeatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gateway_discovery_proto_init() }
func file_proto_gateway_discovery_proto_init() {
	if File_proto_gateway_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_discovery_proto_rawDesc), len(file_proto_gateway_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_discovery_proto_goTypes,
		DependencyIndexes: file_proto_gateway_discovery_proto_depIdxs,
		MessageInfos:      file_proto_gateway_discovery_proto_msgTypes,
	}.Build()
	File_proto_gateway_discovery_proto = out.File
	file_proto_gateway_discovery_proto_goTypes = nil
	file_proto_gateway_discovery_proto_depIdxs = nil
}
